apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    run: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
