name: Master workflow

# Trigger the workflow on push or pull request,
# but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  test-lint-build-and-push:

    runs-on: ubuntu-latest
    env:
      working-directory: ./hello-world

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant permisions to gradlew
        run: chmod +x gradlew
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: ./gradlew test
        working-directory: ${{env.working-directory}}

      - name: Run lint
        run: ./gradlew ktlintCheck
        working-directory: ${{env.working-directory}}

      - name: Build and push docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: john41/kotlin-spring-boot-starter
          tag: latest
          workdir: ${{env.working-directory}}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
